### PR TITLE
feat(generators): differentiate requests/clients test files

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: -

### Changes included:

test file names should differ for Python otherwise the runner won't start the tests due to ambiguity, I only applied this to python but wdyt of adding such suffix to every files just for simplicity?

### CODE REVIEW

**Review by Fluf22 — APPROVED** [review]
It's a good idea, as you wish!
Overall, it's just that you'll have to handle language casing differences 😄 
Maybe just do it in another PR so it doesn't block you from doing other things in Python?

**Comment by millotp** [comment]
having them in different folders isn't enough ?

**Comment by shortcuts** [comment]
> It's a good idea, as you wish! Overall, it's just that you'll have to handle language casing differences 😄 

yup we already have an helper for that, it can just be adding the suffix and let the helper convert

> having them in different folders isn't enough ?

nope it doesn't look like so, even if you have different test classes

**Comment by millotp** [comment]
Also some languages have a strict file pattern like `go`, where the test should end in `_test.go` otherwise it won't run them

**Comment by shortcuts** [comment]
> Also some languages have a strict file pattern like `go`, where the test must end in `_test.go` otherwise it won't run them

I guess if we do like the python client, e.g. `Requests|Client + extension` it should work everywhere

**Comment by shortcuts** [comment]
oki we can abort, definiting each folder as a separate module works, I can just add a template file for that

**Pull request closed without merging**
