### PR TITLE
chore: make Java breaking changes non blocking

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: -

### Changes included:

It's not possible to easily debug issues like https://github.com/algolia/api-clients-automation/pull/1474 as the artifact is not generated when the CI fails, and therefore the file not accessible. This PR changes the CI check to be non blocking but to print the file if it exists

### CODE REVIEW

**Comment by shortcuts** [comment]
I've ported the change to https://github.com/algolia/api-clients-automation/pull/1474 to see if it works

**Comment by shortcuts** [comment]
> I've ported the change to #1474 to see if it works

all good

**Review by millotp — COMMENTED** [review]
I'm not sure that's the point of the check, it should fail if the public API changed, unless the PR title starts with `feat!` for example

**Comment by shortcuts** [comment]
> I'm not sure that's the point of the check, it should fail if the public API changed, unless the PR title starts with `feat!` for example

yes it make sense but the clients are not yet GA, we can keep it and print it but changes are expected

BTW the changes I've made are additions and shouldn't be considered as breaking changes, which is weird

**Pull request merged**
