### PR TITLE
fix(specs): remove input from auth list

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

The auth list endpoint doesn't return the `input` field.
Fixed the `description` for locales.
Make `scope` not required.

### CODE REVIEW

**Review by damcou — DISMISSED** [review]
🦄

**Review by shortcuts — APPROVED** [review]
looks great!

**Review by Fluf22 — APPROVED** [review]
🪨

**Review by shortcuts — APPROVED** [review]
snobbé @Fluf22

**Pull request merged**
