### PR TITLE
chore(snippets): add build step

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

Add a build step to snippets to check that they are correct.

### CODE REVIEW

**Review by Fluf22 — APPROVED** [review]
🆗

**Review by shortcuts — DISMISSED** [review]

**Comment by millotp** [comment]
wait this should be a draft its not working

**Comment by millotp** [comment]
ok this is good now, not many snippets are actually being built, but its better than nothing

**Review by shortcuts — APPROVED** [review]
gg good addition

**Pull request merged**
