### PR TITLE
feat(go): add generateSecuredApiKey helper

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

🎟 JIRA Ticket: [DI-1782](https://algolia.atlassian.net/browse/DI-1782)

Add `GenerateSecuredApiKey` to the go client, also fix the type and the playground

[DI-1782]: https://algolia.atlassian.net/browse/DI-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by morganleroi — APPROVED** [review]
Did you manage to try it in real condition to see if the Search API accept the key and correctly applies to restrictions ? (Even with randomness)

**Comment by millotp** [comment]
yes it's working well now, thanks for making me test !

**Review by morganleroi — APPROVED** [review]
👏🏼

**Review by shortcuts — APPROVED** [review]
Lovely! The description of the pr needs to be updated but no biggy

**Comment by millotp** [comment]
> The description of the pr needs to be updated but no biggy

updated !

**Pull request merged**
