### PR TITLE
docs: fix action in delete-objects.mdx

### PR DESCRIPTION
**Pull request by larskristianhaga**
## 🧭 What and Why

Seems like the documentation is wrong for the new Java client. Specifically the part when deleting an object based ObjectId. 
Using `DELETE` deletes the entire index, and not just deleting the single object based on ObjectId. It should instead be `DELETE_OBJECT`.

🎟 JIRA Ticket:
None

### Changes included: 
Documentation changes

- Update `delete-objects.mdx` Java documentation for deletion of object based on objectId.

## 🧪 Test
None, updated documentation to reflect the actual functionality.

### CODE REVIEW

**Review by shortcuts — COMMENTED** [review]
Good catch thanks for contributing!! Can you fix the others too please? go also uses the wrong enum

**Review by larskristianhaga — COMMENTED** [review]
Fixed documentation for Delete Object for `csharp`, `go`, `dart`, and `Kotlin`.

**Review by larskristianhaga — COMMENTED** [review]
Fixed documentation for Delete Object for csharp, go, dart, and Kotlin.

**Review by shortcuts — DISMISSED** [review]
thanks a lot for your contribution!!

**Pull request closed without merging**
