### PR TITLE
feat(javascript): add search wrappers to lite client

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2746

### Changes included:

Provide the search wrappers to the JavaScript `algoliasearch/lite` package

closes https://github.com/algolia/algoliasearch-client-javascript/issues/1536#issuecomment-2292597045

### CODE REVIEW

**Comment by millotp** [comment]
would be interesting to see the bundle size on this one

**Comment by shortcuts** [comment]
> would be interesting to see the bundle size on this one

yup im adding the check

**Comment by shortcuts** [comment]
still way lighter than v4, great

**Review by millotp — APPROVED** [review]
gg

**Review by millotp — DISMISSED** [review]

**Review by Fluf22 — DISMISSED** [review]
👍🏻

**Comment by shortcuts** [comment]
sorry guys @Fluf22 @millotp

**Review by millotp — APPROVED** [review]

**Pull request merged**
