### PR TITLE
chore(ci): remove gradle wrapper validation from all languages

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket:

I don't think it improves the CI time but we download the bundle validation for java on every clients which it isn't needed

### CODE REVIEW

**Review by morganleroi — APPROVED** [review]
nice !

**Review by millotp — COMMENTED** [review]
the wrapper is used for all language, without the validation we are open to code injection

**Comment by shortcuts** [comment]
> the wrapper is used for all language, without the validation we are open to code injection

ah? isn't it what validates the java bundle with the current one?

**Comment by millotp** [comment]
no this is another step https://github.com/algolia/api-clients-automation/blob/main/.github/workflows/check.yml#L348

**Comment by shortcuts** [comment]
oh shoot aborting then D: great catch ty

**Pull request closed without merging**
