### PR TITLE
chore: correctly delete python on pregen

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: -

### Changes included:

the snake cased folders were not deleted, resulting in the query_suggestions client being outdated

### CODE REVIEW

**Review by millotp — APPROVED** [review]
good catch, I have the same issue for ruby actually

**Comment by shortcuts** [comment]
> good catch, I have the same issue for ruby actually

I guess you can leverage the same stuff!

**Comment by millotp** [comment]
yep I'll do it in my open PR

**Comment by shortcuts** [comment]
removing automerge just to check if the CI deletes the code correctly

**Pull request merged**
