### PR TITLE
chore(deps): use bodinsamuel/renovate-automatic-branch

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

Uses https://github.com/bodinsamuel/renovate-automatic-branch to remove logic from renovate, and test the action.

### Changes included:

- Fix the regex error
- Add the action
- Remove the custom code

## 🧪 Test

Wait until friday 16h

### CODE REVIEW

**Review by bodinsamuel — APPROVED** [review]
👀

**Comment by millotp** [comment]
can everyone approve PR's now that it's public ? I don't think you could do that before

**Comment by bodinsamuel** [comment]
I think I always was able to but not merge. You can double check with @shortcuts

**Comment by shortcuts** [comment]
> can everyone approve PR's now that it's public ? I don't think you could do that before

Yup everyone in the company, it has always been the case

**Pull request merged**
