### PR TITLE
fix(cts): add more tests for query params

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

Add a test for list and space serialization in query parameters.

### CODE REVIEW

**Comment by morganleroi** [comment]
Nice ! Do we check our beloved langage and fix here if needed ?

**Comment by morganleroi** [comment]
@millotp adds stuff everyday to my todo-list. 🗡️

**Comment by millotp** [comment]
idk I'm waiting for a reply [here](https://algolia.slack.com/archives/C044KTYBSQY/p1706623572937919?thread_ts=1706608084.304679&cid=C044KTYBSQY)

**Review by Fluf22 — APPROVED** [review]
LET'S GO

**Review by morganleroi — APPROVED** [review]
INSANE ! What a collaboration ! Better than the ISS collaboration !

**Pull request merged**
