### PR TITLE
chore(scripts): catch up on deprecated github actions

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

🎟 JIRA Ticket: [DI-923](https://algolia.atlassian.net/browse/DI-923)

We have a lot of deprecation warning, for node 12 and for the `set-output` thing, but it's not supported in js so we have to do a [workaround](https://github.com/actions/toolkit/issues/1218#issuecomment-1288890856) until this is fixed.

[DI-923]: https://algolia.atlassian.net/browse/DI-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by shortcuts — DISMISSED** [review]
looks perfect!

**Comment by millotp** [comment]
it's only superficially unfortunately, the matrix is empty but should be full :(

**Comment by shortcuts** [comment]
> it's only superficially unfortunately, the matrix is empty but should be full :(

oh wow indeed, was I looking at the wrong run?

**Comment by millotp** [comment]
the `setOutput` in js only works for the first call and then nothing

**Review by shortcuts — APPROVED** [review]
:okidoki: gg

**Pull request merged**
