### PR TITLE
feat(dart): add Dio HttpClientAdapter to ClientOptions

### PR DESCRIPTION
**Pull request by techouse**
## 🧭 What and Why

This PR gives the user the ability to optionally provide a custom Dio [`HttpClientAdapter`](https://pub.dev/documentation/dio/latest/dio/HttpClientAdapter-class.html), i.e.

```dart
final SearchClient client = SearchClient(
  appId: 'foo',
  apiKey: 'bar',
  options: ClientOptions(
    httpClientAdapter: NativeAdapter(), // <-- from https://pub.dev/packages/native_dio_adapter
  ),
);
```

Via this option users can configure [Dio](https://pub.dev/packages/dio) to use [native_dio_adapter](https://pub.dev/packages/native_dio_adapter) which uses [cupertino_http](https://pub.dev/packages/cupertino_http) on iOS and [cronet_http](https://pub.dev/packages/cronet_http) on Android to delegate HTTP requests to the native platform instead of the `dart:io` platforms.

The advantages of using [cronet_http](https://pub.dev/packages/cronet_http) are:
 - It automatically supports Android platform features such as HTTP proxies.
 - It supports configurable caching.
 - It supports more HTTP features such as HTTP/3.

The advantages of using [cupertino_http](https://pub.dev/packages/cupertino_http) are:
- It automatically supports iOS/macOS platform features such VPNs and HTTP proxies.
- It supports many more configuration options such as only allowing access through WiFi and blocking cookies.
- It supports more HTTP features such as HTTP/3 and custom redirect handling.

### Changes included:

- add `HttpClientAdapter?` to `ClientOptions`

---

Supersedes https://github.com/algolia/algoliasearch-client-dart/pull/13
Addresses https://github.com/algolia/algoliasearch-client-dart/issues/12

### CODE REVIEW

**Review by shortcuts — COMMENTED** [review]
looks awesome, thanks a lot for the contribution

@aallam wdyt?

**Comment by techouse** [comment]
Not sure why the codegen job fails 😅

**Comment by shortcuts** [comment]
> Not sure why the codegen job fails 😅

ah we provide a ref which might not work with forks D:

**Comment by techouse** [comment]
> > Not sure why the codegen job fails 😅
> 
> ah we provide a ref to the checkout action which might not work with forks D:

Ah, makes sense. Bots and their permissions 🙈

**Review by aallam — APPROVED** [review]
Nice! we already have interceptors, and I see no issue of adding `HttpClientAdapter` too.

**Comment by shortcuts** [comment]
All CTS should fail because of e2e, I'll open a PR with your commits and merge them into main

**Comment by shortcuts** [comment]
ah nvm there's no e2e for dart, all good then

**Comment by shortcuts** [comment]
superseded by https://github.com/algolia/api-clients-automation/pull/3326 thanks a lot @techouse for the contribution!!

**Comment by shortcuts** [comment]
(i'll co author you obviously)

**Comment by techouse** [comment]
Roger that 🫡

**Pull request closed without merging**
