### PR TITLE
chore: openapi metadata files

### PR DESCRIPTION
**Pull request by aallam**
## 🧭 What and Why

OpenAPI generators metadata files are pushed (and removed) from API clients repositories, although not useful for those repos.

### Changes included:

Ignore OpenAPI generators metadata files.

### CODE REVIEW

**Review by millotp — COMMENTED** [review]
I think the file `.openapi-generator-ignore` is useful for generation, but we can replace it by editing the generator directly.

**Review by shortcuts — COMMENTED** [review]
actually I know why JS ignore all of that, is because the folder structure is so different from what's proposed by the default generator that we've removed every supported files, and therefore don't need it.

---

maybe it's just a git issue? I know some . files are not always tracked but not sure why it added/removed them

**Review by Fluf22 — APPROVED** [review]
Let's go with this if there is no pushback

**Comment by Fluf22** [comment]
_There was, indeed, pushback_

**Pull request closed without merging**
