### PR TITLE
fix(php): Deprecation warning fix for PHP 8.1+

### PR DESCRIPTION
**Pull request by aykutersoy**
Native return types added for `offsetExists`, `offsetGet`, `offsetSet`, `offsetUnset` methods

## 🧭 What and Why
See: https://github.com/algolia/api-clients-automation/issues/3561

I had two option to get rid of deprecation messages, either add native types or add this `#[\ReturnTypeWillChange]` attribute. I opted in for native types.

🎟 JIRA Ticket: -

### Changes included:

- List changes
- native return types added for `offsetExists`, `offsetGet`, `offsetSet`, `offsetUnset` methods

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey @aykutersoy thanks for trying out the client and providing a fix :) I've reverted some changes because they are generated files, changing the mustache one is enough

**Review by shortcuts — APPROVED** [review]
looks great, thanks for the contribution!

**Comment by aykutersoy** [comment]
Dang it!

@shortcuts There's one more method needs native return type 
`clients/algoliasearch-client-php/lib/Model/AbstractModel::jsonSerialize()`
Shall I create another PR or leave it with you?

**Comment by shortcuts** [comment]
> Dang it!
> 
> @shortcuts There's one more method needs native return type `clients/algoliasearch-client-php/lib/Model/AbstractModel::jsonSerialize()` Shall I create another PR or leave it with you?

if you need it asap it would be best for you to directly contribute, otherwise we can log it on our side and tackle that later

**Comment by aykutersoy** [comment]
> if you need it asap it would be best for you to directly contribute, otherwise we can log it on our side and tackle that later

Done! Thank you 🙌

**Pull request merged**
