### PR TITLE
fix(go): true speed of benchmark

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

Don't run benchmark in `race` mode because it kills the perfs

### CODE REVIEW

**Comment by shortcuts** [comment]
ooooh that will be FAST

**Comment by shortcuts** [comment]
(btw this is a chore we shouldn't put it in the changelog)

**Review by shortcuts — DISMISSED** [review]
nothing to add! waiting for the gen, it looks great

**Comment by millotp** [comment]
> (btw this is a chore we shouldn't put it in the changelog)

The name of the commit doesn't determine the changelog anymore, only if there are changes in the clients folder.
I guess this should be a fix(benchmark) maybe

**Review by shortcuts — APPROVED** [review]
> > (btw this is a chore we shouldn't put it in the changelog)
> 
> The name of the commit doesn't determine the changelog anymore, only if there are changes in the clients folder. I guess this should be a fix(benchmark) maybe

true but still a chore IMO, non blocking anyway, great fix!

**Pull request merged**
