### PR TITLE
chore: prepare release 2024-02-02

### PR DESCRIPTION
**Pull request by millotp**
## Summary

This PR has been created using the `yarn release` script. Once merged, the clients will try to release their new version if their version has changed.

## Version Changes

- csharp: 7.0.0-alpha.6 -> **`prerelease` _(e.g. 7.0.0-alpha.7)_**
- ~dart: 1.5.0 -> **`patch` _(e.g. 1.5.1)_**~
  - No `feat` or `fix` commit, thus unchecked by default.
- go: 4.0.0-alpha.44 -> **`prerelease` _(e.g. 4.0.0-beta.0)_**
- java: 4.0.0-beta.19 -> **`prerelease` _(e.g. 4.0.0-beta.20)_**
- javascript: 5.0.0-alpha.101 -> **`prerelease` _(e.g. 5.0.0-alpha.102)_**
- kotlin: 3.0.0-beta.13 -> **`prerelease` _(e.g. 3.0.0-beta.14)_**
- php: 4.0.0-alpha.93 -> **`prerelease` _(e.g. 4.0.0-alpha.94)_**
- ~python: 4.0.0b3 -> **`patch` _(e.g. 4.0.0b4)_**~
  - No `feat` or `fix` commit, thus unchecked by default.
- ~ruby: 3.0.0.alpha.6 -> **`patch` _(e.g. 3.0.0.alpha.7)_**~
  - No `feat` or `fix` commit, thus unchecked by default.
- scala: 2.0.0-alpha.6 -> **`prerelease` _(e.g. 2.0.0-alpha.7)_**
- swift: 9.0.0-alpha.3 -> **`prerelease` _(e.g. 9.0.0-alpha.4)_**

### Skipped Commits

<p>It doesn't mean these commits are being excluded from the release. It means they're not taken into account when the release process figured out the next version number, and updated the changelog.</p>

<details>
  <summary>
    <i>Commits without language scope:</i>
  </summary>

  
</details>

<details>
  <summary>
    <i>Commits with unknown language scope:</i>
  </summary>

  - fix(cts): add test for _snippetResult (#2645)
- chore(deps): bump aiohttp from 3.9.1 to 3.9.2 in /clients/algoliasearch-client-python (#2635)
- fix(scripts): push origin for new docs (#2632)
</details>

### CODE REVIEW

**Review by Fluf22 — DISMISSED** [review]
☑️

**Comment by millotp** [comment]
sorry @Fluf22 you were too fast, I added a commit to promote go to beta !

**Comment by Fluf22** [comment]
I didn't know today was d-day 😮

**Review by Fluf22 — APPROVED** [review]
✅

**Pull request merged**
