### PR TITLE
chore: prepare release 2024-02-13

### PR DESCRIPTION
**Pull request by millotp**
## Summary

This PR has been created using the `yarn release` script. Once merged, the clients will try to release their new version if their version has changed.

## Version Changes

- csharp: 7.0.0-alpha.7 -> **`prerelease` _(e.g. 7.0.0-alpha.8)_**
- ~dart: 1.5.0 (no commit)~
- ~go: 4.0.0-beta.0 (no commit)~
- ~java: 4.0.0-beta.20 (no commit)~
- ~javascript: 5.0.0-alpha.102 (no commit)~
- ~kotlin: 3.0.0-beta.14 (no commit)~
- php: 4.0.0-alpha.94 -> **`prerelease` _(e.g. 4.0.0-alpha.95)_**
- python: 4.0.0b3 -> **`patch` _(e.g. 4.0.0b4)_**
- ruby: 3.0.0.alpha.6 -> **`minor` _(e.g. 3.0.0.alpha.7)_**
- ~scala: 2.0.0-alpha.7 (no commit)~
- ~swift: 9.0.0-alpha.4 (no commit)~

### Skipped Commits

<p>It doesn't mean these commits are being excluded from the release. It means they're not taken into account when the release process figured out the next version number, and updated the changelog.</p>

<details>
  <summary>
    <i>Commits without language scope:</i>
  </summary>

  
</details>

<details>
  <summary>
    <i>Commits with unknown language scope:</i>
  </summary>

  - fix(cts): add e2e for abtesting (#2673)
- chore(deps): dependencies 2024-02-12 (#2682)
- fix(cts): strict comparaison of query parameters (#2681)
- fix(cts): add more tests for query params (#2641)
- chore(deps): dependencies 2024-02-05 (#2648)
- fix(scripts): kotlin release (#2649)
</details>

### CODE REVIEW

**Comment by millotp** [comment]
there should be every languages here

**Review by shortcuts — APPROVED** [review]
Looks good, however somes fixes were done in a cts scope meaning it doesn't trigger releases, we should either support cts in the release trigger or use proper scopes

**Comment by shortcuts** [comment]
IMHO update the trigger scope to support cts and re-run the release script

**Comment by millotp** [comment]
I don't think scopes are reliable, we should do the git diff to determine what to update

**Comment by shortcuts** [comment]
> I don't think scopes are reliable, we should do the git diff to determine what to update

as long as we keep skipping chore and properly use `chore` when editing stuff outside of the client, why not

**Pull request closed without merging**
