### PR TITLE
chore(scripts): update gradle to v8

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

gradle 8 is required by some of our dependencies, like #1342.

### CODE REVIEW

**Review by shortcuts — DISMISSED** [review]
does it have an impact on the generated client?

**Comment by millotp** [comment]
shouldn't have, it's just tooling and we don't use many custom gradle plugin yet (wait until @aallam changes everything ahah)

**Review by aallam — DISMISSED** [review]
Nice! :D this should also improve build speed and `.kts` support! :D

**Comment by millotp** [comment]
rebasing to get the debian image, and now it works locally and on the CI :)

**Review by shortcuts — APPROVED** [review]
_GG_

**Pull request merged**
