### PR TITLE
feat(specs): add support for widgets / banners in search for the csharp client

### LINKED ISSUE #3869: [bug]: RenderingContent is missing widgets section
### Description

The .NET client does not map the widgets / banner image in the renderingContent section of the api response. After setting up a rule in the merchandising studio that dictate that a banner should be returned for certain queries, i noticed that the rendering content model in the search response is missing the widgets field. When doing the query in the algolia dashboard i can see that the json response from the api contains the expected fields

### Language

CSharp

### Client

Search

### Steps to reproduce

1. Go to the merchandising studio and create a rule that should return a banner for a given query
2. Execute the query you specified in step 1 through the .NET client
3. In the response you can see that the rendering content is missing the expected field for widgets

OR
just go here: https://github.com/algolia/api-clients-automation/blob/main/clients/algoliasearch-client-csharp/algoliasearch/Models/Search/RenderingContent.cs and see that the whole widgets field is missing from the model

### Relevant log output

_No response_

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by Kalmar99**
fix #3869

## 🧭 What and Why
The csharp client currently does not support Widgets / Banners as part of the RenderingContent model, however this feature is now available in the dashboard / merchandising studio. This PR adds the missing models required for parsing banners from the api response.

### Changes included:
Adds the following models:
- Banner
- BannerImage
- BannerImageUrl
- BannerLink
- Widgets
Also added the missing widgets field to the RenderingContent model

### CODE REVIEW

**Comment by millotp** [comment]
Hey, all the files you edited are generated files, all the files in this folder are generated, can you edit the spec in `specs/search` please ? You don't to push the generated code, the CI will do it for you

**Comment by Kalmar99** [comment]
Ah, i dident notice that this was all auto generated 😅 Will update my PR in a bit

**Comment by Kalmar99** [comment]
I updated the PR now, removing the models and updating the schema, however i am struggling with setting up the environment for building this. Followed your guide as outlined here https://api-clients-automation.netlify.app/docs/setup-repository but running into a very ambiguous error with the linter 

`Error: command failed: yarn specs:lint common
    at run (C:\projects\other\api-clients-automation\scripts\common.ts:114:13)
    at async lintCommon (C:\projects\other\api-clients-automation\scripts\specs\format.ts:28:3)
    at async buildSpecs (C:\projects\other\api-clients-automation\scripts\specs\index.ts:149:3)
    at async Command.<anonymous> (C:\projects\other\api-clients-automation\scripts\cli\index.ts:125:5)`

Any chance you could look over the schema and try to build it to see if i did it correctly? 😇

**Review by millotp — APPROVED** [review]
The CI is red but the changes looks good ! Thanks for the contribution

**Comment by Kalmar99** [comment]
@millotp Thank you for helping me sort this out! Massive kudos for responding so fast, going to have some thrilled marketers at our company when this is released :)

**Pull request merged**
