### PR TITLE
chore(cts): remove new line at the end of templates

### PR DESCRIPTION
**Pull request by millotp**
## 🧭 What and Why

This is a bit pointless, but my editor is configured to add new line at the end of files, which is great, except for mustache.
This PR adds a custom eslint parser and rule to remove new lines at the end of plain text files, like mustache.

### CODE REVIEW

**Review by shortcuts — APPROVED** [review]
you should try neovim, it doesn't add newlines for mustaches

**Comment by millotp** [comment]
I'm not the only one using the repo, anyone can push mustache with new lines at the end, this just makes it easy to fix !

**Comment by shortcuts** [comment]
> I'm not the only one using the repo, anyone can push mustache with new lines at the end, this just makes it easy to fix !

__anyone should try neovim right__

**Review by shortcuts — APPROVED** [review]
jokes aside, great addition :)

**Review by shortcuts — APPROVED** [review]

**Review by shortcuts — APPROVED** [review]

**Pull request merged**
