### PR TITLE
fix(specs): a/b testing

### PR DESCRIPTION
**Pull request by kai687**
## 🧭 What and Why

Update the A/B testing spec to improve the reference content.

### Changes included:

- The `configuration` object wasn't included yet
- Status is an enum
- Headers for rate-limiting info

### CODE REVIEW

**Comment by Fluf22** [comment]
I pushed a fix for Swift: filenames need to be unique

**Review by Fluf22 — APPROVED** [review]
Nice improvements!
I'm curious to learn about `x-additionalPropertiesName` though 🤔

**Comment by shortcuts** [comment]
> > Nice improvements! I'm curious to learn about `x-additionalPropertiesName` though 🤔
> 
> [It's a vendor extension from redoc (for better documentation)](https://redocly.com/docs/api-reference-docs/specification-extensions/x-additional-properties-name/#x-additionalpropertiesname)

I don't think it's reflected on the doc atm, is it? 🤔

**Comment by shortcuts** [comment]
> @shortcuts it should. See `revenueSignificance` for the "Retrieve A/B test details" response. It shows 'currency code'. Without it, it would show 'property name' (see the published version of the same endpoint).
> 
> 

ahhhh oki I see, that's super nice!

**Pull request merged**
