### PR TITLE
chore: renovate for Python

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: -

### Changes included:

as per https://docs.renovatebot.com/modules/manager/regex/#required-fields, we must capture the depname if it doesn't match a specific template. This should do it

### CODE REVIEW

**Review by millotp — APPROVED** [review]
nice

**Comment by millotp** [comment]
you need to wait for the CI to push the generated commit on main

**Comment by shortcuts** [comment]
> you need to wait for the CI to push the generated commit on main

for normal commits it's fine, it's for releases that it breaks

**Comment by shortcuts** [comment]
> > you need to wait for the CI to push the generated commit on main
> 
> for normal commits it's fine, it's for releases that it breaks

but I can wait otherwise I'll steal your authoring on the 90k deletion

**Pull request merged**
