### PR TITLE
feat(php): add `chunkedBatch` method

### PR DESCRIPTION
**Pull request by damcou**
## 🧭 What and Why

🎟 JIRA Ticket: DI-1832

### Changes included:

- Add method `chunkedBatch` and use it in `replaceAllObjects`

### CODE REVIEW

**Review by morganleroi — COMMENTED** [review]
Can you add a unit test to check that we do call X times method and correctly chunk the batch ?

**Comment by shortcuts** [comment]
> > Can you add a unit test to check that we do call X times method and correctly chunk the batch ?
> 
> Where are we regarding helper tests ? I see that only a few languages have them, shouldn't we wait for the helpers to be added to the specs before adding them ?

you can follow python and javascript they should be fairly close to reality, errors will be fixed in an upcoming pr from @millotp

**Comment by morganleroi** [comment]
Seems weird to me to push code without associated tests. Even if helpers signature will be generated, you will have to implement the test. Up to you.

**Comment by damcou** [comment]
Since it's not only about this method, I'll dedicate a whole ticket/PR about helper tests (it may take a while)

**Review by morganleroi — APPROVED** [review]

**Pull request merged**
