### PR TITLE
chore(ci): retry setup if it fails

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 JIRA Ticket: -

### Changes included:

swift constantly fails the setup step, we can add the small retry logic like in DI since it's a server error we can't control

### CODE REVIEW

**Review by morganleroi — APPROVED** [review]
Let's try !

**Comment by Fluf22** [comment]
Let's put 10 ?
It's awful how it's unstable these days...
I'm gonna go check the og repo if there are more info than last time

**Review by Fluf22 — APPROVED** [review]
retry.fml

**Comment by shortcuts** [comment]
closing this since when it fails, it fails for a good amount of time so... retrying doesn't help

**Pull request closed without merging**
