### PR TITLE
fix(python): wait for task helper

### PR DESCRIPTION
**Pull request by kai687**
## 🧭 What and Why

This PR attempts to fix a bug in the `wait_for_task` helper due to a wrong signature.

<details>
<summary>Error triggering code</summary>

```py
import asyncio

from algoliasearch.search.client import SearchClient

app_id = ...
api_key = ...
index_name = ...

async def search():
    client = SearchClient(app_id, api_key)
    res = await client.save_object(
        index_name=index_name,
        body={"title": "test record"},
    )

    res = await client.wait_for_task(index_name=index_name, task_id=res.task_id)
    print(res)
    await client.close()


if __name__ == "__main__":
    asyncio.run(search())
```

</details>

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "search.py", line 23, in <module>
    asyncio.run(search())
  File "python/latest/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "python/latest/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python/latest/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "search.py", line 17, in search
    res = await client.wait_for_task(index_name=index_name, task_id=res.task_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_env/lib/python3.12/site-packages/algoliasearch/search/client.py", line 199, in wait_for_task
    return await create_iterable(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "_env/lib/python3.12/site-packages/algoliasearch/http/helpers.py", line 54, in create_iterable
    return await retry()
           ^^^^^^^^^^^^^
  File "_env/lib/python3.12/site-packages/algoliasearch/http/helpers.py", line 46, in retry
    if error_validate is not None and error_validate(resp):
                                      ^^^^^^^^^^^^^^^^^^^^
TypeError: SearchClient.wait_for_task.<locals>.<lambda>() takes 0 positional arguments but 1 was given
```

### Changes included:

- Change type annotation for `task_id` to `int`
- add (unused) argument to the lambda function in `error_validate`

### CODE REVIEW

**Review by Fluf22 — APPROVED** [review]
✅

**Review by millotp — CHANGES_REQUESTED** [review]
this looks good thanks for the fix ! just waiting for the release to finish

**Comment by Fluf22** [comment]
@kai687 we need to wait for the current release to finish before being able to merge your PR, otherwise, the release process will fail.
We will unblock the PR and send you a message when it'll be done!

**Review by millotp — APPROVED** [review]
all good you can merge whenever you want :)

**Pull request merged**
