### PR TITLE
feat(specs): update Insights API spec

### PR DESCRIPTION
**Pull request by kai687**
## 🧭 What and Why

Update the API spec for the Insights API we wanted to make an update to 'Purchase' events.

We want to remove the event-level `queryID` parameter in the documentation for 'Purchase' events, and rather have object-level `queryID`s. (Otherwise, it's too confusing).

🎟 JIRA Ticket: n/a

### Changes included:

- Add the 'value' parameter to the 'AddToCart' and 'Purchase' events. 
- Remove the event level `queryID` parameter from the 'Purchase' events.
- Some other minor edits (mostly sorting and formatting, making things more consistent).

## 🧪 Test

n/a

### CODE REVIEW

**Comment by shortcuts** [comment]
hey @kai687, thanks for the PR, taking a look!

**Comment by shortcuts** [comment]
the last issue remaining is that the echo interceptor for java requires the method to return the request, but since there's no payload we can't do that, will try to find a fix for that (cc @millotp)

**Comment by morganleroi** [comment]
working on a C# fix.

**Review by millotp — APPROVED** [review]
finally green ! gg everyone

**Pull request merged**
