### PR TITLE
fix(specs): numberOfPendingTasks is plural

### PR DESCRIPTION
**Pull request by kai687**
## 🧭 What and Why

This PR aims to improve the specs for the `listIndicesResponse` schema.

Testing the `/1/indexes` endpoint, I found that `numberOfPendingTasks` should be plural.

This PR also adds default values for `pendingTask` (`false`) and `numberOfPendingTasks` (`0`) as both values always seem to be part of the response.

🎟 JIRA Ticket: N/A

### Changes included:

- fix name of response parameter `numberOfPendingTasks`
- Add default values for `numberOfPendingTasks` and `pendingTask`
- Make `numberOfPendingTasks` required for `listIndicesResponse`
- Make `primary` and `replicas` nullable

### CODE REVIEW

**Review by shortcuts — DISMISSED** [review]
Great catch, thanks!

**Comment by shortcuts** [comment]
> If numberOfPendingTasks is always present in the response, should this be marked as a required property?

Yep indeed

> Should primary and replicas be marked as nullable with default values of null if they're optional parameters?

As long as they are not required it should be interpreted correctly by the language, but it might make sense in some cases 🤔

**Review by shortcuts — APPROVED** [review]
looks great!

**Comment by shortcuts** [comment]
@kai687 will you try your 2nd question in this PR or can I merge?

**Comment by kai687** [comment]
@shortcuts sorry, got side-tracked.

**Comment by shortcuts** [comment]
> @shortcuts sorry, got side-tracked.

no problem!

**Comment by kai687** [comment]
So, I guess making `replicas` and `primary` nullable with `null` as default values broke the code gen.

**Comment by shortcuts** [comment]
> So, I guess making `replicas` and `primary` nullable with `null` as default values broke the code gen.

oops D: yep indeed it looks like

**Review by shortcuts — APPROVED** [review]

**Comment by shortcuts** [comment]
Thanks again!

**Pull request merged**
